# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"audio_extensions": "00_Core_Signal.ipynb",
         "get_audio_files": "00_Core_Signal.ipynb",
         "AudioGetter": "00_Core_Signal.ipynb",
         "URLs.SPEAKERS10": "00_Core_Signal.ipynb",
         "URLs.SPEAKERS250": "00_Core_Signal.ipynb",
         "URLs.ESC50": "00_Core_Signal.ipynb",
         "tar_extract_at_filename": "00_Core_Signal.ipynb",
         "AudioTensor": "00_Core_Signal.ipynb",
         "show_audio_signal": "00_Core_Signal.ipynb",
         "OpenAudio": "00_Core_Signal.ipynb",
         "AudioBlock": "00_Core_Signal.ipynb",
         "AudioSpectrogram": "01_Core_Spectrogram.ipynb",
         "show_spectrogram": "01_Core_Spectrogram.ipynb",
         "AudioToSpec": "01_Core_Spectrogram.ipynb",
         "SpectrogramTransformer": "01_Core_Spectrogram.ipynb",
         "fill_pipeline": "01_Core_Spectrogram.ipynb",
         "warn_unused": "01_Core_Spectrogram.ipynb",
         "get_usable_kwargs": "01_Core_Spectrogram.ipynb",
         "AudioToMFCC": "01_Core_Spectrogram.ipynb",
         "config_from_func": "02_Core_Config_Pipeline.ipynb",
         "AudioConfig": "02_Core_Config_Pipeline.ipynb",
         "RemoveSilence": "10_Augment_Preprocess.ipynb",
         "Resample": "10_Augment_Preprocess.ipynb",
         "CropSignal": "11_Augment_Signal.ipynb",
         "shift_signal": "11_Augment_Signal.ipynb",
         "SignalShifter": "11_Augment_Signal.ipynb",
         "AddNoise": "11_Augment_Signal.ipynb",
         "AudioTensor.apply_gain": "11_Augment_Signal.ipynb",
         "ChangeVolume": "11_Augment_Signal.ipynb",
         "AudioTensor.cutout": "11_Augment_Signal.ipynb",
         "SignalCutout": "11_Augment_Signal.ipynb",
         "AudioTensor.lose_signal": "11_Augment_Signal.ipynb",
         "SignalLoss": "11_Augment_Signal.ipynb",
         "DownmixMono": "11_Augment_Signal.ipynb",
         "CropTime": "12_Augment_Spectrogram.ipynb",
         "MaskFreq": "12_Augment_Spectrogram.ipynb",
         "MaskTime": "12_Augment_Spectrogram.ipynb",
         "SGRoll": "12_Augment_Spectrogram.ipynb",
         "Delta": "12_Augment_Spectrogram.ipynb",
         "TfmResize": "12_Augment_Spectrogram.ipynb"}

modules = ["core/signal.py",
           "core/spectrogram.py",
           "core/config.py",
           "augment/preprocess.py",
           "augment/signal.py",
           "augment/spectrogram.py"]

doc_url = "https://rbracco.github.io/fastai2_audio/"

git_url = "https://github.com/rbracco/fastai2_audio/tree/master/"

def custom_doc_links(name): return None
